### ISSUE TITLE
Not compatible with VSCode Insiders

### ISSUE THREAD

**Issue by ReticentFacade** [dexxiez/shadcn-hsl-preview#1]
Wasn't able to install 'dexxiez.shadcn-color-preview' extension because it is not compatible with the current version of Visual Studio Code - Insiders (version 1.85.0-insider).

What can we do about this?

**Comment by dexxiez** [comment]
Hi @ReticentFacade 

Can you make sure you're updated to the latest stable of VSCode which is version of `1.89` or the current insiders build which is `1.90-insider`. Is there a specific reason you're staying on the insider build of 1.85?
