### ISSUE TITLE
Feature Request: Support HSL Color Preview in JS, JSX, TS, and TSX Files

### ISSUE THREAD

**Issue by diegourday** [dexxiez/shadcn-hsl-preview#12]
Hi there,

Could you add HSL color preview support for JS, JSX, TS, and TSX files? It works great in CSS, and having it in these other file types would be extremely helpful for consistency.

My use case:
I'm using this code in a `theme-colors.js` file for toggling between different color themes.

![Captura de pantalla 2024-07-30 020247](https://github.com/user-attachments/assets/e92d5e74-4f80-45ea-9755-0a68deae044f)

**Comment by dexxiez** [comment]
Hi @diegourday, I have merged this feature for you in [v1.3.0](https://github.com/dexxiez/shadcn-hsl-preview/releases/tag/v1.3.0) and it should now be deployed.
