### ISSUE TITLE
Feature request — convert HEX to HSL

### ISSUE THREAD

**Issue by innocenzi** [dexxiez/shadcn-hsl-preview#3]
Would be nice to be able to paste some HEX like that:
```css
--background: #0C0A09;
```

And be able to run a "Convert to HSL" command that would convert it to that:
```css
--background: 20 14.3% 4.1%;
```

**Comment by dexxiez** [comment]
@innocenzi, Thanks for the feature request. This has been merged and published. Hopefully this covers your use case. Let me know how you go.

![Convert Demo](https://github.com/dexxiez/shadcn-hsl-preview/raw/main/images/convert.gif?raw=true "Demo Time")

**Comment by innocenzi** [comment]
Awesome, works perfectly. Thank you!
